FROM node:18-slim 

RUN adduser --disabled-password --gecos "" appuser

WORKDIR /app

COPY package*.json tsconfig.json ./

RUN npm install --omit=dev

COPY . .

RUN npx tsc

RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 8000

CMD ["node", "app.js"]
